# Testing Gradience

In [1]:
import numpy as np

from gradience.tensor import Tensor
from gradience.autograd.autograd_engine import AutogradEngine

### Step 1: Testing Tensor creation

In [2]:
x = Tensor([[1, 2, 3],
            [4, 5, 6]], requires_grad=True)
print(x)
print(x.data)
print(x.shape)
print(x.dtype)
print(x.size)
print(x.requires_grad)
print(x.is_leaf)
print(x.grad)
print(x.grad_fn)

Tensor(data=[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32, requires_grad=True, is_leaf=True)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
float32
6
True
True
None
None


### Testing Add Operation.

In [3]:
x = Tensor([1, 2, 3], requires_grad=True)
y = Tensor([4, 5, 6], requires_grad=True)

z = x + y 

print(z)
print(z.data)
print(z.is_leaf)
print(z.grad_fn)
print(z.grad_fn.operation)
print(z.grad_fn.parents)

print("-" * 80)

w = x * y

print(w)
print(w.data)
print(w.is_leaf)
print(w.grad_fn)
print(w.grad_fn.operation)
print(w.grad_fn.parents)


Tensor(data=[5. 7. 9.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=False)

[5. 7. 9.]
False
<class 'gradience.ops.add.AddOp'>
(Tensor(data=[1. 2. 3.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=True)
, Tensor(data=[4. 5. 6.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=True)
)
--------------------------------------------------------------------------------
Tensor(data=[ 4. 10. 18.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=False)

[ 4. 10. 18.]
False
<class 'gradience.ops.multiply.MultOp'>
(Tensor(data=[1. 2. 3.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=True)
, Tensor(data=[4. 5. 6.], shape=(3,), dtype=float32, requires_grad=True, is_leaf=True)
)


#### Backward Pass:

In [4]:
# AutogradEngine.backward(z)
# print(z.grad)

In [5]:
x = Tensor([2.0], requires_grad=True)
y = Tensor([3.0], requires_grad=True)

a = x * y
b = x + y

print(a.grad_fn.parents)

# AutogradEngine.backward(a)

print(x.grad)
print(y.grad)

(Tensor(data=[2.], shape=(1,), dtype=float32, requires_grad=True, is_leaf=True)
, Tensor(data=[3.], shape=(1,), dtype=float32, requires_grad=True, is_leaf=True)
)
None
None


### checking for gradient accumulation.

In [7]:
# Test 1:
x = Tensor([2], requires_grad=True)

a = x * x

# a.backward()

# Test 2:
y = Tensor([3], requires_grad=True)

m = x * y
n = m + x

n.backward()

print(x.grad)
print(y.grad)


[4.]
[2.]
