# Testing Gradience

In [1]:
import numpy as np

from gradience.tensor import Tensor
from gradience.autograd.context import Context
from gradience.ops.add import AddOp

### Step 1: Testing Tensor creation

In [2]:
x = Tensor([[1, 2, 3],
            [4, 5, 6]], requires_grad=True)
print(x)
print(x.data)
print(x.shape)
print(x.dtype)
print(x.size)
print(x.requires_grad)
print(x.is_leaf)
print(x.grad)
print(x.grad_fn)

Tensor(data=[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32, requires_grad=True)
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
float32
6
True
True
None
None


### Testing Operations.

In [5]:
x = Tensor([1, 2, 3], requires_grad=True)
y = Tensor([4, 5, 6], requires_grad=True)

z = x + y 
print(z)
print(z.data)
print(z.is_leaf)

Tensor(data=[5. 7. 9.], shape=(3,), dtype=float32, requires_grad=True)
[5. 7. 9.]
False
